"""Adiciona_modelo_Peca_e_relacao_Servico_Peca

Revision ID: 6084eb38f964
Revises: 
Create Date: 2026-07-16 19:51:15.957029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6084eb38f964'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('alerta_estoque_minimo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('servicos_pecas',
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_usada', sa.Integer(), nullable=False),
    sa.Column('preco_unitario_no_servico', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('servico_id', 'peca_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicos_pecas')
    op.drop_table('pecas')
    # ### end Alembic commands ###
